plugins {
    id 'com.android.application'
}

android {
    namespace 'com.grimforsaken.towerbugs'
    compileSdk 36

    defaultConfig {
        applicationId 'com.grimforsaken.towerbugs.frogdefense.v020'
        minSdk 23
        targetSdk 33
        versionCode 4
        versionName '0.2.0'
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
